# Generated by Django 3.1.11 on 2021-08-14 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajinkya', '0003_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='quotes',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ajinkya/images/'),
            preserve_default=False,
        ),
    ]
